### ISSUE TITLE
Resource Page Issues 

### ISSUE THREAD

**Issue by hamstersaredevs** [quub/marketplace-issues#1]
I have found various issues on the resources page.
![Screenshot_20200509-170202](https://user-images.githubusercontent.com/53443191/81486332-a77c4b80-9219-11ea-8587-4464cd42bdc8.png)
![Screenshot_20200509-170150](https://user-images.githubusercontent.com/53443191/81486336-b06d1d00-9219-11ea-9489-0ad85c2c158f.png)

- Jäger

**Comment by robertdrakedennis** [comment]
This is why we dont let havila edit my layouts

**Comment by robertdrakedennis** [comment]
Somewhat fixed this. Will be back for another round of polish at some point. Thanks for the issue!
